enum UserType {
  STUDENT
  TUTOR
}

enum AttendanceStatus {
  PRESENT
  ABSENT
  LATE
}

type Attendance {
  id: ID!
  courseScheduleId: ID!
  userId: ID!
  userType: UserType!
  status: AttendanceStatus!
  attendanceDate: Date!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  courseSchedule: CourseSchedule!
  user: User!
}

type MeetingLinkResponse {
  attendance: Attendance
  meetingLink: String
  remainingTimeMinutes: String
}

extend type Query {
  attendances(batchId: ID!): [Attendance!]!
  attendance(id: ID!): Attendance!
}

extend type Mutation {
  getCourseMeetingLink(courseScheduleId: ID!): MeetingLinkResponse!
  getBatchMeetingLink(batchId: ID!): MeetingLinkResponse!
  deleteAttendance(id: ID!): Boolean!
}
