enum InstructorRole {
  MAIN
  ASSISTANT
}

type BatchInstructor {
  id: ID!
  userId: ID!
  batchCourseId: ID!
  role: InstructorRole!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  user: User!
  batchCourse: BatchCourse!
}


input CreateBatchInstructorInput {
  userId: ID!
  batchCourseId: ID!
  role: InstructorRole!
}

input UpdateBatchInstructorInput {
  userId: ID
  batchCourseId: ID
  role: InstructorRole
}

extend type Query {
  instructors(batchId: ID): [BatchInstructor!]!
  instructor(id: ID!): BatchInstructor
}

extend type Mutation {
  createInstructor(input: CreateBatchInstructorInput!): BatchInstructor!
  updateInstructor(id: ID!, input: UpdateBatchInstructorInput!): BatchInstructor!
  deleteInstructor(id: ID!): Boolean!
}
