type BatchCommunity {
  id: ID!
  batchId: ID!
  userId: ID!
  content: String!
  isEdited: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  batch: Batch!
  user: User!
  reactions: [CommunityReactions!]!
  comments: [CommunityComment!]!
  attachments: [CommunityAttachmentFiles!]!
}

extend type Query {
  communities(batchId: ID): [BatchCommunity!]!
  community(id: ID!): BatchCommunity!
}

extend type Mutation {
  postCommunity(batchId: ID!, content: String!): BatchCommunity!
  updateCommunity(id: ID!, content: String!): BatchCommunity!
  deleteCommunity(id: ID!): Boolean!
}

extend type Subscription {
  communityUpdated(batchId: ID!): BatchCommunity!
}
