enum EnrollmentStatus {
  APPLIED
  ENROLLED
  COMPLETED
  DROPPED
}

type BatchEnrollment {
  id: ID!
  profileId: ID!
  batchId: ID!
  enrollmentDate: Date!
  completionDate: Date
  status: EnrollmentStatus!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  profile: StudentProfile!
  batch: Batch!
  skill: Skill
  payments: [Payment!]!
}

input UpdateEnrollmentInput {
  batchId: ID
  profileId: ID
  status: EnrollmentStatus
}

extend type Query {
  enrollments(batchId: ID!): [BatchEnrollment!]!
  enrollment(id: ID!): BatchEnrollment!
}

extend type Mutation {
  createEnrollment(batchId: ID!, studentId: ID): BatchEnrollment!
  updateEnrollment(id: ID!, input: UpdateEnrollmentInput!): BatchEnrollment!
  deleteEnrollment(id: ID!): Boolean!
}