type Certificate {
  id: ID!
  skillId: ID!
  result: String!
  certificateHtml: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  skill: Skill!
}

extend type Query {
  certificates(enrollmentId: ID!): [Certificate!]!
  certificate(id: ID!): Certificate
}

extend type Mutation {
  generateCertificate(input: GenerateCertificateInput!): Certificate!
  deleteCertificate(id: ID!): Boolean!
}

input GenerateCertificateInput {
  skillId: ID!
}
