type Certificate {
  id: ID!
  skillId: ID!
  result: String!
  certificateHtml: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  skill: Skill!
}

# extend type Query {
#   certificates
#   certificate
# }

# extend type Mutation {
#   generateCertificate
#   deleteCertificate
# }