type CommunityAttachmentFiles {
  id: ID!
  communityId: ID!
  fileName: String!
  filePath: String!
  fileExtension: String!
  fileSize: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  community: BatchCommunity!
}

extend type Query {
  communityAttachments(communityId: ID): [CommunityAttachmentFiles!]!
  communityAttachment(id: ID!): CommunityAttachmentFiles!
}

extend type Mutation {
  addAttachments(communityId: ID!, files: [AttachmentInput!]!): [CommunityAttachmentFiles!]!
  addAttachment(communityId: ID!, fileName: String!, filePath: String!, fileExtension: String!, fileSize: Int!): CommunityAttachmentFiles!
  deleteAttachment(id: ID!): Boolean!
}

input AttachmentInput {
  fileName: String!
  filePath: String!
  fileExtension: String!
  fileSize: Int!
}
