type CommunityAttachmentFiles {
  id: ID!
  communityId: ID!
  fileName: String!
  filePath: String!
  fileExtension: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  community: BatchCommunity!
}
