type CommunityComment {
  id: ID!
  communityId: ID!
  userId: ID!
  content: String!
  isEdited: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  community: BatchCommunity!
  user: User!
  reactions: [CommentReactions!]!
}

extend type Query {
  comments(communityId: ID): [CommunityComment!]!
  comment(id: ID!): CommunityComment!
}

extend type Mutation {
  postComment(communityId: ID!, content: String!): CommunityComment!
  updateComment(id: ID!, content: String!): CommunityComment!
  deleteComment(id: ID!): Boolean!
}
