type Course {
  id: ID!
  name: String!
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  materials: [CourseMaterial!]!
  batchCourses: [BatchCourse!]!
}

extend type Query {
  courses: [Course!]!
  course(id: ID!): Course
  myCourses: [BatchCourse!]!
}

extend type Mutation {
  createCourse(input: CreateCourseInput!): Course!
  updateCourse(id: ID!, input: UpdateCourseInput!): Course!
  deleteCourse(id: ID!): Boolean!
}

input CreateCourseInput {
  name: String!
  description: String
}

input UpdateCourseInput {
  name: String
  description: String
}
