type CourseSchedule {
  id: ID!
  scheduleId: ID!
  batchCourseId: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  schedule: Schedule!
  batchCourse: BatchCourse!
  attendances: [Attendance!]!
}


extend type Query {
  courseSchedules(batchCourseId: ID): [CourseSchedule!]!
  courseSchedule(id: ID!): CourseSchedule
}

extend type Mutation {
  createCourseSchedule(input: CreateCourseScheduleInput!): CourseSchedule!
  updateCourseSchedule(id: ID!, input: UpdateCourseScheduleInput!): CourseSchedule!
  deleteCourseSchedule(id: ID!): Boolean!
}


input CreateCourseScheduleInput {
  scheduleId: ID!
  batchCourseId: ID!
}

input UpdateCourseScheduleInput {
  scheduleId: ID
  batchCourseId: ID
}
