input UpdateArticleInput {
  title: String
  faviconUrl: String
  description: String
  pageUrl: String
}

type LessonOnlineArticles {
  id: ID!
  lessonId: ID!
  title: String!
  faviconUrl: String
  description: String
  pageUrl: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  lesson: ModuleLessons!
}

extend type Query {
  articles(lessonId: ID!): [LessonOnlineArticles!]!
  article(id: ID!): LessonOnlineArticles!
}

extend type Mutation {
  updateArticle(id: ID!, input: UpdateArticleInput!): LessonOnlineArticles!
  deleteArticle(id: ID!): Boolean!
}
