input UpdateVocabularyInput {
  vocabulary: String
  meaning: String
  description: String
}

type LessonVocabularies {
  id: ID!
  lessonId: ID!
  vocabulary: String!
  meaning: String!
  description: String
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  lesson: ModuleLessons!
}

extend type Query {
  vocabularies(lessonId: ID!): [LessonVocabularies!]!
  vocabulary(id: ID!): LessonVocabularies!
}

extend type Mutation {
  updateVocabulary(id: ID!, input: UpdateVocabularyInput!): LessonVocabularies!
  deleteVocabulary(id: ID!): Boolean!
}
