input UpdateVideoInput {
  title: String
  thumbnailUrl: String
  description: String
  videoUrl: String
}

type LessonYouTubeVideos {
  id: ID!
  lessonId: ID!
  title: String!
  thumbnailUrl: String
  description: String
  videoUrl: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  lesson: ModuleLessons!
}

extend type Query {
  videos(lessonId: ID!): [LessonYouTubeVideos!]!
  video(id: ID!): LessonYouTubeVideos!
}

extend type Mutation {
  updateVideo(id: ID!, input: UpdateVideoInput!): LessonYouTubeVideos!
  deleteVideo(id: ID!): Boolean!
}
