type LessonInteractions {
  id: ID!
  lessonId: ID!
  question: String!
  answer: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  lesson: ModuleLessons!
}
