type LessonInteractions {
  id: ID!
  lessonId: ID!
  studentQuestion: String!
  aiAnswer: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  lesson: ModuleLessons!
}

input CreateLessonInteractionInput {
  lessonId: ID!
  question: String!
}

extend type Query {
  lessonInteractions(lessonId: ID!): [LessonInteractions!]!
  lessonInteraction(id: ID!): LessonInteractions
}

extend type Mutation {
  createLessonInteraction(input: CreateLessonInteractionInput!): LessonInteractions!
  deleteLessonInteraction(id: ID!): Boolean!
}
