type MaterialFiles {
  id: ID!
  materialId: ID!
  fileName: String!
  filePath: String!
  fileExtension: String!
  fileSize: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  material: CourseMaterial!
}

extend type Query {
  materialFiles(materialId: ID!): [MaterialFiles!]!
  materialFile(id: ID!): MaterialFiles
}

extend type Mutation {
  uploadMaterialFile(materialId: ID!, file: Upload!): MaterialFiles!
  deleteMaterialFile(id: ID!): Boolean!
}
