input UpdateModuleInput {
  name: String
  description: String
  displayOrder: Int
  isLocked: Boolean
}

type Modules {
  id: ID!
  profileId: ID!
  name: String!
  description: String
  displayOrder: Int!
  isLocked: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  profile: StudentProfile!
  lessons: [ModuleLessons!]!
}

extend type Query {
  modules(profileId: ID!): [Modules!]!
  module(id: ID!): Modules!
}

extend type Mutation {
  updateModule(id: ID!, input: UpdateModuleInput!): Modules!
  deleteModule(id: ID!): Boolean!
}
