input UpdateLessonInput {
  title: String
  content: String
  displayOrder: Int
  isCompleted: Boolean
  isLocked: Boolean
}

type ModuleLessons {
  id: ID!
  moduleId: ID!
  title: String!
  content: String!
  displayOrder: Int!
  isCompleted: Boolean!
  isLocked: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  module: Modules!
  vocabularies: [LessonVocabularies!]!
  onlineArticles: [LessonOnlineArticles!]!
  youtubeVideos: [LessonYouTubeVideos!]!
  interactions: [LessonInteractions!]!
}

extend type Query {
  lessons(moduleId: ID!): [ModuleLessons!]!
  lesson(id: ID!): ModuleLessons!
}

extend type Mutation {
  completeLesson(id: ID!): ModuleLessons!
  updateLesson(id: ID!, input: UpdateLessonInput!): ModuleLessons!
  deleteLesson(id: ID!): Boolean!
}
