type Notification {
  id: ID!
  userId: ID!
  title: String!
  content: String!
  isRead: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  user: User!
}

extend type Query {
  notifications(userId: ID!): [Notification!]!
  notification(id: ID!): Notification
}

extend type Mutation {
  sendNotification(input: SendNotificationInput!): Notification!
  markAsReadNotification(id: ID!): Notification!
  markAsReadAllNotifications: Boolean!
  deleteNotification(id: ID!): Boolean!
}

input SendNotificationInput {
  userId: ID!
  title: String!
  content: String!
}
