enum PaymentStatus {
  PENDING
  COMPLETED
  FAILED
}

type Payment {
  id: ID!
  enrollmentId: ID!
  amount: Float!
  currency: String!
  method: String
  status: PaymentStatus!
  paidAt: DateTime
  transactionId: String
  checkoutUrl: String
  receiptUrl: String
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  enrollment: BatchEnrollment!
}

extend type Query {
  payments(enrollmentId: ID, status: PaymentStatus): [Payment!]!
  payment(id: ID!): Payment!
}

extend type Mutation {
  makePayment(enrollmentId: ID!): Payment!
  cancelPayment(id: ID!): Payment!
  deletePayment(id: ID!): Boolean!
}
