enum AgeRange {
  UNDER_18
  _18_25
  _26_35
  _36_45
  _45_PLUS
}

enum Proficiency {
  BEGINNER
  BASIC
  INTERMEDIATE
  ADVANCED
}

enum DurationUnit {
  DAYS
  WEEKS
  MONTHS
  YEARS
}

input CreateProfileInput {
  ageRange: AgeRange!
  proficiency: Proficiency!
  nativeLanguage: String!
  learningGoal: String!
  targetDuration: Int!
  durationUnit: DurationUnit!
  constraints: String
}

input UpdateProfileInput {
  ageRange: AgeRange
  proficiency: Proficiency
  nativeLanguage: String
  learningGoal: String
  targetDuration: Int
  durationUnit: DurationUnit
  constraints: String
}

input UpdateLearningPlanInput {
  improvements: String!
}

type StudentProfile {
  id: ID!
  userId: ID!
  ageRange: AgeRange!
  proficiency: Proficiency!
  nativeLanguage: String!
  learningGoal: String!
  targetDuration: Int!
  durationUnit: DurationUnit!
  constraints: String
  aiLearningPlan: String
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  user: User!
  modules: [Modules!]!
  freeConversations: [FreeConversation!]!
  batchEnrollments: [BatchEnrollment!]!
}

extend type Query {
  myProfile: StudentProfile
  studentProfile(userId: ID!): StudentProfile!
}

extend type Mutation {
  createProfile(input: CreateProfileInput!): StudentProfile!
  updateProfile(input: UpdateProfileInput!): StudentProfile!
  generateLearningPlan: StudentProfile!
  updateLearningPlan(input: UpdateLearningPlanInput!): StudentProfile!
  installLearningPlan: StudentProfile!
  deletePlan: StudentProfile!
  deleteProfile: Boolean!
}
