enum UserRole {
  ADMIN
  STUDENT
  TUTOR
  UNDETERMINED
}

enum RegisterUserRole {
  STUDENT
  UNDETERMINED
}

input RegisterInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  role: RegisterUserRole
}

input LoginInput {
  email: String!
  password: String!
}

input UpdateUserInput {
  firstName: String
  lastName: String
  email: String
  password: String
  role: UserRole
  isVerified: Boolean
}

input UpdateMeInput {
  firstName: String
  lastName: String
  email: String
  password: String
}

input VerifyInput {
  email: String!
  verificationCode: String!
}

input ResendVerificationInput {
  email: String!
}

type AuthResponse {
  user: User!
  accessToken: String!
  refreshToken: String!
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  role: UserRole!
  isVerified: Boolean!
  accessToken: String
  refreshToken: String
  createdAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
  deletedAt: DateTime
  # Relationships
  profile: StudentProfile
  batchInstructors: [BatchInstructor!]!
  batchCommunities: [BatchCommunity!]!
  communityReactions: [CommunityReactions!]!
  communityComments: [CommunityComment!]!
  commentReactions: [CommentReactions!]!
  feedbacks: [Feedback!]!
  notifications: [Notification!]!
  attendances: [Attendance!]!
  verificationCodes: [VerificationCode!]!
}

extend type Query {
  users(pagination: PaginationInput): [User!]!
  user(id: ID!): User!
  me: User!
}

extend type Mutation {
  register(input: RegisterInput!): Boolean!
  verify(input: VerifyInput!): Boolean!
  resendVerification(input: ResendVerificationInput!): Boolean!
  login(input: LoginInput!): AuthResponse!
  logout: Boolean!
  refreshToken: String!

  updateUser(input: UpdateUserInput!): User!
  updateMe(input: UpdateMeInput!): User!

  deleteUser(id: ID!): Boolean!
  deleteMe: Boolean!
}
