# Import all models to register them with SQLAlchemy
from .user import User
from .verification_code import VerificationCode
from .student_profile import StudentProfile
from .batch_instructor import BatchInstructor
from .batch_community import BatchCommunity
from .community_reactions import CommunityReactions
from .community_comment import CommunityComment
from .comment_reactions import CommentReactions
from .feedback import Feedback
from .notification import Notification
from .attendance import Attendance
from .batch import Batch
from .batch_course import BatchCourse
from .batch_enrollment import BatchEnrollment
from .certificate import Certificate
from .community_attachment_files import CommunityAttachmentFiles
from .course_material import CourseMaterial
from .course_schedule import CourseSchedule
from .course import Course
from .free_conversation import FreeConversation
from .interactions import Interactions
from .lesson_interactions import LessonInteractions
from .lesson_online_articles import LessonOnlineArticles
from .lesson_vocabularies import LessonVocabularies
from .lesson_youtube_videos import LessonYouTubeVideos
from .material_files import MaterialFiles
from .module_lessons import ModuleLessons
from .modules import Modules
from .payment import Payment
from .quiz_results import QuizResults
from .quiz import Quiz
from .schedule import Schedule
from .skill_result import SkillResult
from .skill_tests import SkillTests
