import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS } from '../../src/constants';
export const modal = StyleSheet.create({
    backdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    card: {
        width: '100%',
        maxWidth: 400,
        borderRadius: 32,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1E3A5F',
        backgroundColor: '#0A1628',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
    },
    gradientBg: { ...StyleSheet.absoluteFillObject, opacity: 0.8 },
    iconWrap: {
        height: 160,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
    },
    ring: {
        position: 'absolute',
        width: 100,
        height: 100,
        borderRadius: 100,
        borderWidth: 2,
        borderColor: '#F59E0B30',
    },
    checkCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: '#F59E0B',
        shadowOpacity: 0.5,
        shadowRadius: 15,
    },
    headline: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 15,
        color: '#9CA3AF',
        textAlign: 'center',
        paddingHorizontal: 24,
        lineHeight: 22,
        marginBottom: 32,
    },
    features: {
        paddingHorizontal: 24,
        gap: 12,
        marginBottom: 32,
    },
    featureRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        backgroundColor: '#0F1B33',
        padding: 14,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#1E2D44',
    },
    featureIconWrap: {
        width: 44,
        height: 44,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    featureName: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 2,
    },
    featureDesc: {
        fontSize: 12,
        color: '#6B7280',
    },
    cta: {
        margin: 24,
        marginTop: 0,
        borderRadius: 18,
        overflow: 'hidden',
    },
    ctaGradient: {
        height: 60,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
    },
    ctaText: {
        color: '#1A1A2E',
        fontSize: 17,
        fontWeight: 'bold',
    },
    // Chapa Redirect Button
    payNowBtn: {
        width: '100%',
        height: 56,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 12,
        elevation: 4,
        shadowColor: '#F59E0B',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    payNowGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    payNowText: {
        color: '#1A1A2E',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
});
export default StyleSheet.create({
    container: { flex: 1 },
    centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    scroll: { padding: SPACING.lg, paddingBottom: 140 },

    loadingText: { marginTop: SPACING.md, color: '#9CA3AF', fontSize: 15 },

    errorCard: {
        backgroundColor: '#1A1A2E',
        borderRadius: BORDER_RADIUS.xl,
        padding: SPACING.xl,
        alignItems: 'center',
        gap: SPACING.sm,
    },
    errorTitle: { color: '#EF4444', fontSize: 20, fontWeight: 'bold' },
    errorSub: { color: '#9CA3AF', textAlign: 'center', lineHeight: 20 },
    retryBtn: {
        backgroundColor: '#F59E0B',
        paddingHorizontal: SPACING.xl,
        paddingVertical: SPACING.sm,
        borderRadius: BORDER_RADIUS.full,
        marginTop: SPACING.sm,
    },
    retryText: { color: '#1A1A2E', fontWeight: 'bold' },

    header: { alignItems: 'center', marginBottom: SPACING.xl, position: 'relative' },
    headerGlow: {
        position: 'absolute', top: -20, width: 260, height: 120,
        borderRadius: 130,
    },
    headerIcon: {
        width: 72, height: 72, borderRadius: 36,
        backgroundColor: '#F59E0B22',
        alignItems: 'center', justifyContent: 'center',
        marginBottom: SPACING.md,
        borderWidth: 1, borderColor: '#F59E0B44',
    },
    title: { fontSize: 26, fontWeight: 'bold', color: '#fff', marginBottom: 6 },
    subtitle: { fontSize: 14, color: '#9CA3AF' },

    amountCard: {
        borderRadius: BORDER_RADIUS.xl,
        padding: SPACING.xl,
        alignItems: 'center',
        marginBottom: SPACING.lg,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#F59E0B33',
    },
    amountCardGrad: { ...StyleSheet.absoluteFillObject },
    amountLabel: { fontSize: 13, color: '#9CA3AF', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 1 },
    amountValue: { fontSize: 42, fontWeight: 'bold', color: '#F59E0B' },
    amountCurrency: { fontSize: 20, fontWeight: '600', color: '#F59E0BAA' },
    statusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: SPACING.sm },
    statusDot: { width: 8, height: 8, borderRadius: 4 },
    statusText: { color: '#D1D5DB', fontSize: 13, fontWeight: '600' },

    unlockBox: {
        backgroundColor: '#0F1B33',
        borderRadius: BORDER_RADIUS.xl,
        padding: SPACING.lg,
        marginBottom: SPACING.lg,
        borderWidth: 1,
        borderColor: '#1E3A5F',
    },
    unlockTitle: { color: '#fff', fontWeight: 'bold', fontSize: 16, marginBottom: SPACING.md },
    unlockRow: {
        flexDirection: 'row', alignItems: 'center', gap: SPACING.sm,
        paddingVertical: 10,
        borderBottomWidth: 1, borderBottomColor: '#1E2D44',
    },
    unlockIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    unlockLabel: { flex: 1, color: '#D1D5DB', fontSize: 14 },

    gatewayBox: {
        backgroundColor: '#0D1626',
        borderRadius: BORDER_RADIUS.xl,
        padding: SPACING.xl,
        alignItems: 'center',
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: '#1E2D44',
        gap: SPACING.sm,
    },
    gatewayText: { color: '#9CA3AF', fontSize: 14, fontWeight: '600' },
    gatewayHint: { color: '#6B7280', fontSize: 12, textAlign: 'center', lineHeight: 18 },
    reopenBtn: {
        flexDirection: 'row', alignItems: 'center', gap: 6,
        marginTop: SPACING.sm,
        borderWidth: 1, borderColor: '#F59E0B55',
        borderRadius: BORDER_RADIUS.full,
        paddingHorizontal: SPACING.md, paddingVertical: 8,
        backgroundColor: '#F59E0B11',
    },
    reopenBtnText: { color: '#F59E0B', fontSize: 13, fontWeight: '600' },

    secureBadge: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 5, marginBottom: SPACING.sm,
    },
    secureText: { color: '#4B5563', fontSize: 12 },

    footer: {
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: '#0A1628',
        padding: SPACING.lg,
        paddingBottom: Platform.OS === 'ios' ? 36 : SPACING.lg,
        borderTopWidth: 1, borderTopColor: '#1E2D44',
    },
    verifyBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 8, backgroundColor: '#F59E0B',
        paddingVertical: 16, borderRadius: BORDER_RADIUS.lg,
        shadowColor: '#F59E0B', shadowOpacity: 0.4, shadowRadius: 12, shadowOffset: { width: 0, height: 4 },
        elevation: 6,
    },
    verifyBtnDisabled: { opacity: 0.6, shadowOpacity: 0 },
    verifyText: { color: '#1A1A2E', fontWeight: 'bold', fontSize: 16 },
    devTestBtn: {
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
        gap: 5, paddingVertical: 8, marginTop: 6,
        borderWidth: 1, borderColor: '#2D3748', borderRadius: BORDER_RADIUS.md,
        borderStyle: 'dashed',
    },
    devTestText: { color: '#4B5563', fontSize: 12 },
    cancelBtn: { alignItems: 'center', paddingVertical: SPACING.sm, marginTop: SPACING.xs },
    cancelText: { color: '#6B7280', fontWeight: '600' },

    statusCheckBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: 'transparent',
        paddingVertical: 12,
        borderRadius: BORDER_RADIUS.lg,
        borderWidth: 1,
        borderColor: COLORS.primary + '44',
        marginTop: SPACING.md,
    },
    statusCheckBtnDisabled: { opacity: 0.5 },
    statusCheckText: { color: COLORS.primary, fontWeight: '600', fontSize: 14 },
});
