import { StyleSheet } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS } from '../../src/constants/theme';
export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#080C14',
    },
    heroBanner: {
        paddingTop: 60,
        paddingHorizontal: 24,
        paddingBottom: 30,
        overflow: 'hidden',
    },
    glowBlob: {
        position: 'absolute', top: -30, right: -30,
        width: 180, height: 180, borderRadius: 90,
        backgroundColor: 'rgba(16,185,129,0.1)',
    },
    header: {
        gap: 8,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        color: '#fff',
        letterSpacing: -0.5,
    },
    subtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.5)',
        fontWeight: '600',
    },
    planContainer: {
        flex: 1,
    },
    planCard: {
        backgroundColor: 'rgba(255,255,255,0.04)',
        padding: 24,
        margin: 20,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    h3: {
        fontSize: 22,
        fontWeight: '800',
        color: COLORS.primary,
        marginTop: 24,
        marginBottom: 12,
    },
    h4: {
        fontSize: 18,
        fontWeight: '700',
        color: '#fff',
        marginTop: 16,
        marginBottom: 8,
    },
    textLine: {
        fontSize: 15,
        lineHeight: 24,
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 6,
    },
    boldLine: {
        fontSize: 15,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 6,
    },
    bullet: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.7)',
        lineHeight: 24,
        marginLeft: 10,
        marginBottom: 6,
    },
    loadingOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
        marginTop: 60,
    },
    loadingText: {
        marginTop: 20,
        fontSize: 16,
        color: 'rgba(255,255,255,0.5)',
        fontWeight: '600',
    },
    improveContainer: {
        padding: 24,
        paddingBottom: 40,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        backgroundColor: '#080C14',
    },
    improveInput: {
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 16,
        padding: 16,
        fontSize: 15,
        height: 120,
        color: '#fff',
        backgroundColor: 'rgba(255,255,255,0.05)',
        textAlignVertical: 'top',
    },
    improveButtons: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 16,
    },
    cancelButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
    },
    cancelButtonText: {
        color: 'rgba(255,255,255,0.5)',
        fontWeight: '600',
        fontSize: 15,
    },
    submitImproveButton: {
        borderRadius: 14,
        overflow: 'hidden',
        minWidth: 140,
    },
    improveBtnGrad: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        alignItems: 'center',
    },
    submitImproveButtonText: {
        color: '#fff',
        fontWeight: '800',
        fontSize: 15,
    },
    footer: {
        padding: 24,
        paddingBottom: 40,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        flexDirection: 'row',
        gap: 16,
        backgroundColor: '#080C14',
    },
    primaryButton: {
        flex: 2,
        borderRadius: 18,
        overflow: 'hidden',
    },
    primaryButtonGrad: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 16,
        gap: 10,
    },
    primaryButtonText: {
        color: '#fff',
        fontWeight: '800',
        fontSize: 16,
    },
    secondaryButton: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        borderRadius: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    secondaryButtonText: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 15,
        fontWeight: '700',
    },
    errorText: {
        color: '#EF4444',
        textAlign: 'center',
        marginBottom: 10,
        fontWeight: '600',
    },
});
